### ISSUE TITLE
Can you provide customization in below points 

### ISSUE THREAD

**Issue by poonamdhomane** [eBay/NMessenger#168]
If you can provide highly customisation in this library. That will be really great .
If there is provision of customisation for 
1. input view , 
2. message view , 
3. timestamp view like header as in whatsapp (for today, yesterday ....) ,
4. bubble view with background stretchable image for text Node. 

 if this feature available then no need to search for any other library :)  👍

**Comment by dodikk** [comment]
> input view ,

There is a pending PR solving this https://github.com/eBay/NMessenger/pull/129. 
You can try my fork until it's accepted https://github.com/dodikk/NMessenger/blob/latest-fixes/nMessenger/Source/Messenger/Components/InputBarView/NMessengerBarView.swift#L94



---

 > message view ,

It's already customizable. 

---

> timestamp view like header as in whatsapp (for today, yesterday ....) ,

Just assing `ASTextNode` to this property https://github.com/eBay/NMessenger/blob/master/nMessenger/Source/MessageNodes/MessageCell/MessageNode.swift#L39

---

> bubble view with background stretchable image for text Node.

You can subclass and make one. Either in your codebase or in a PullRequest.
The library is just a foundation. It is not supposed to contain everything your particular project needs. Otherwise it would be a bloatware.

Please send a PR if you feel everybody needs that feature. The maintainers will consider it.
** Unfortunately, I'm not one of them yet.

**Comment by dodikk** [comment]
> input view ,

And you can build your own customized subclass of `InputBarView` . You are not forced to use `NMessengerBarView`. It is just a default.

**Comment by dodikk** [comment]
> timestamp view like header as in whatsapp (for today, yesterday ....) ,

There is also an "describe this in docs" issue for this https://github.com/eBay/NMessenger/issues/155

**Comment by dodikk** [comment]
> bubble view with background stretchable image for text Node.

A related dedicated issue. https://github.com/eBay/NMessenger/issues/167

**Comment by poonamdhomane** [comment]
@dodikk  Thank you.
got the points

**Comment by dodikk** [comment]
@iOSUser110 , could you, please, close the issue if the answers were helpful enough and no changes to the codebase are required?
Thanks.
