### ISSUE TITLE
Bounciness

### ISSUE THREAD

**Issue by jyounus** [eBay/NMessenger#19]
Hey there,

I was wondering if you guys are considering adding some UIDynamic animations. The native iOS messages app has this subtle but nice bouncing animation depending on how fast you scroll up/down. 

Check out this link here, there's a gif if you scroll down to demonstrate what I mean: 
```
https://www.objc.io/issues/5-ios7/collection-views-and-uidynamics/
```

Is this something you guys think you could implement?

**Comment by zdenektopic** [comment]
I think NMessenger conversation view is implemented via AS/UITableView so I dont think so. However it should not be too hard to reimplement the whole thing in AS/UICollectionView.

**Comment by jyounus** [comment]
Good point. I've just asked the question over at the ASDK repo. For anyone that's interested in the answer, hopefully you'll be able to find it here (whenever someone replies):

https://github.com/facebook/AsyncDisplayKit/issues/2116


Now a different question for the authors/maintainers of this repo, would you consider adding this to your roadmap or would this be rather something you'd want for someone else to create a PR for?

**Comment by atainter** [comment]
I wouldn't be opposed to adding it. However, I believe most of our layouts rely on the width of the astableview component through layoutspecsthatfit. Changing NMessenger to a collectionview would probably affect most of the messenger components. If our test code coverage was higher, I would feel more comfortable changing it. 

While improving code coverage is a near term goal, I'm not sure when I'll get around to switching the tableview. Once I've improved code coverage and changed the tableview to a collectionview, I'd prefer someone else would submit a PR to integrate UIDynamics since I have no experience with it.

**Comment by jyounus** [comment]
Fair enough, makes sense. Thanks! If I ever do get the chance to try it out, I'll make sure to submit a PR.
