### ISSUE TITLE
Can I disable animation and clear all messages in current view?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [eBay/NMessenger#28]
Hi, I want to clear message and reload data without animation and without scrolling. is that possible only with just sendText()?

**Comment by atainter** [comment]
You'll have to call functions on `NMessenger` instead of `NMessengerViewController` for this.

To clear all messages without animation, you can use `self.messengerView.clearALLMessages()` in NMessengerViewController. Reloading messages is harder since it's not the typical "tableView with data source" model. To reload data you'll have to add all of the messages again. There are a few functions in NMessenger which make it easy to add an array of messages, but you'll have to create those messages first. For example:

```swift
/**
     Adds an array of messages to the messenger.
     - parameter messages: An array of messages
     - parameter scrollsToMessage: If marked true, the tableview will scroll to the newly added
     - parameter animation: An animation for newly added messages
     - parameter completion: A completion handler
     */
    public func addMessagesWithBlock(messages: [GeneralMessengerCell], scrollsToMessage: Bool, withAnimation animation: UITableViewRowAnimation, completion: (()->Void)?)
```

would be called with `self.messengerView.addMessagesWithBlock(...)`. 

There aren't any public functions in `NMessengerViewController` which solely create `GeneralMessengerCell`s for text, image, etc. Would it be helpful to expose those functions?

**Comment by jimmyzzzzzzz** [comment]
Thanks a lot for the reply. After reading your comment I checked NMessengerViewController.swift source code and found a function called postText() which generates a GeneralMessengerCell. Then I called addMessagesWithBlock() and it's finally working.

**Comment by atainter** [comment]
Cool. I think I'm still going to make those functions public.
