### ISSUE TITLE
Alternatives in Objective-C

### ISSUE THREAD

**Issue by lolgear** [eBay/NMessenger#40]
Could you provide alternatives in Objective-C in Readme section?

**Comment by DavidSchechter** [comment]
According to Apple docs (https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/Migration.html):
"Remember that you cannot subclass a Swift class in Objective-C. Therefore, the class you migrate cannot have any Objective-C subclasses in your app."

Because NMessenger is set up to be accessed as a subclass, you cannot use it in Objective C.

**Comment by skensell** [comment]
I just recently open-sourced my Objective-C alternative: https://github.com/skensell/MXRMessenger
