### ISSUE TITLE
Typing indicator

### ISSUE THREAD

**Issue by yarodevuci** [eBay/NMessenger#76]
Can someone post a better explanation for typing indicator?
if I call function `showTypingIndicator` what I need to pass for `ASDisplayNode` ?

**Comment by atainter** [comment]
`func showTypingIndicator(avatar: ASDisplayNode) -> GeneralMessengerCell` this function takes an avatar and returns a reference to the typing indicator you created. 

Now that I look at this, the `avatar` parameter should probably be optional.
Nevertheless, if you don't want to add an avatar, use `showTypingIndicator(ASDisplayNode())`.

Otherwise, you can do something like this:

```swift
let nAvatar = ASImageNode()
nAvatar.image = UIImage(named: "nAvatar")
nAvatar.preferredFrameSize = CGSize(width: 20, height: 20)

let typingIndicator = showTypingIndicator(nAvatar)
```

You can remove it by passing the reference of the typing indicator to the `func removeTypingIndicator(indicator: GeneralMessengerCell)` function

**Comment by yarodevuci** [comment]
@atainter Something like this:
```
let typingIndicator = showTypingIndicator(nAvatar)
 removeTypingIndicator(indicator: typingIndicator)
``` ?

**Comment by atainter** [comment]
yep

**Comment by kurry421** [comment]
@atainter im having trouble with understanding removing the typing indicator...

I have a switch on my db 0/1 that calls a function on my app whenever changed:

`    func observeTyping() {
         if(dbVal  == 1){
           //turn on indicator
            let avatar = ASImageNode()
            let typingIndicator = self.showTypingIndicator(avatar)
         }  
            if(dbVal == 0){
                //turn off indicator
                self.removeTypingIndicator(typingIndicator)
            }
    }`
