### ISSUE TITLE
AsyncDisplayKit 2.0 released

### ISSUE THREAD

**Issue by Sundin** [eBay/NMessenger#82]
AsyncDisplayKit 2.0 released. Any plans on upgrading?

https://github.com/facebook/AsyncDisplayKit/releases/tag/2.0

**Comment by ravikumar578** [comment]
when is the ETA for AsyncDisplayKit 2.0 upgrade.

**Comment by yarodevuci** [comment]
Never, this library sucks bad

**Comment by atainter** [comment]
If anyone wants to submit a PR to change it, I'd be more than happy to merge it. Unfortunately @DavidSchechter and I are working on other things and do not have time to overhaul this library to support 2.0. 

I was really hoping the community would help support NMessenger.

**Comment by yarodevuci** [comment]
Seems like no one has desire to do so. Unfortunate:(

**Comment by alexandremorgado** [comment]
+1

**Comment by jonybur** [comment]
Just posted a pull request that has ASDK 2.1 compatibility. I've been using it for my project.
You can try it out on [this fork](https://github.com/jonybur/NMessenger) branch 'asdk-2.1'

**Comment by astrolka** [comment]
@jonybur Thank you very much! Could you help me with a problem which i confronted with? I cannot understand why `messageTable` gets wrong size and sometimes message is cropped tried to change  with this `let size = message.layoutThatFits(newSize).size` in `MessageGroup.swift` line: 150 but with no effect(((
<img width="309" alt="2017-02-23 14 08 40" src="https://cloud.githubusercontent.com/assets/22860930/23256943/96cf6bec-f9d2-11e6-8e79-3baedbfa17b6.png">

**Comment by jonybur** [comment]
@astrolka Sorry that you encountered that bug! Is it possible for you to send me a snippet of code so I can try to reproduce it on my side? Thank you

**Comment by astrolka** [comment]
@jonybur actually I'm not using custom content node, so here is what i have in my MessengerController class
```
    func insertNewMessages() {
        shouldLoad = false
        viewModel.loadMessages(complition: { (messages) in
            var mesageGroups = [MessageGroup]()
            var lastGroup: MessageGroup!
            var previousVM: MessageViewModel!
            for messageVM in messages.reversed() {
                let textContent = TextContentNode(textMessageString: messageVM.text, currentViewController: self, bubbleConfiguration: self.sharedBubbleConfiguration)
                let message = MessageNode(content: textContent)
                message.cellPadding = self.messagePadding
                message.currentViewController = self
                if lastGroup == nil || previousVM.model.userId != messageVM.model.userId || lastGroup.isIncomingMessage != messageVM.isIncomingMessage {
                    let newGroup = self.createMessageGroupFor(message: messageVM)
                    newGroup.isIncomingMessage = messageVM.isIncomingMessage
                    newGroup.addMessageToGroup(message, completion: nil)
                    mesageGroups.append(newGroup)
                    lastGroup = newGroup
                } else {
                    lastGroup.addMessageToGroup(message, completion: nil)
                }
                previousVM = messageVM
            }
            self.messengerView.addMessages(mesageGroups, scrollsToMessage: false)
            self.messengerView.scrollToLastMessage(animated: false)
            self.shouldLoad = true
        }) { (error) in
            self.shouldLoad = true
        }
    }
```

```
    private func createMessageGroupFor (message: MessageViewModel) -> MessageGroup {
        let group = MessageGroup()
        group.currentViewController = self
        group.cellPadding = messagePadding
        if message.isInChat && message.isIncomingMessage {
            group.avatarNode = createAvatarNode(url: message.avatarImageUrl, group: group)
        }
        group.messageOffset = 3
        return group
    }
    
    private func createAvatarNode (url: URL?, group: MessageGroup) -> ASNetworkImageNode {
        let imgSize: CGFloat = Util.isIpad() ? 20 : 40
        let img = ASNetworkImageNode.createWith(size: imgSize)
        img.url = url
        img.delegate = group
        return img
    }
```

**Comment by astrolka** [comment]
@jonybur here are the extensions:

```
extension MessageGroup: ASNetworkImageNodeDelegate {
    public func imageNode(_ imageNode: ASNetworkImageNode, didLoad image: UIImage) {
        setNeedsLayout()
    }
}
```


```
extension ASNetworkImageNode {
    static func createWith(size: CGFloat) -> ASNetworkImageNode {
        let img = ASNetworkImageNode()
        img.style.width = ASDimensionMakeWithPoints(size)
        img.style.height = ASDimensionMakeWithPoints(size)
        img.backgroundColor = UIColor(white: 0.9, alpha: 1.0)
        img.clipsToBounds = true
        img.contentMode = .scaleAspectFill
        img.placeholderFadeDuration = 0.5
        img.cornerRadius = size / 2
        img.imageModificationBlock = { (image) -> UIImage in
            var modifiedImage: UIImage!
            let rect = CGRect(x: 0, y: 0, width: image.size.width, height: image.size.height)
            
            UIGraphicsBeginImageContextWithOptions(image.size, false, UIScreen.main.scale)
            
            UIBezierPath(roundedRect: rect, cornerRadius: size/2).addClip()
            
            image.draw(in: rect)
            modifiedImage = UIGraphicsGetImageFromCurrentImageContext()
            
            UIGraphicsEndImageContext()
            
            return modifiedImage
        }
        return img
    }
}
```

**Comment by jonybur** [comment]
Thank you @astrolka , I will check it out ASAP

**Comment by astrolka** [comment]
@jonybur Thank you, I have solved this problem. [Here is opened issue](https://github.com/eBay/NMessenger/issues/93)

**Comment by atainter** [comment]
I updated the ASDK branch to remove most of the 2.1 deprecation warnings. Message group updates [still] don't work. It's an issue with the way animations were structured and will need a rewrite. I should have some time this weekend to work on it.

**Comment by appleguy** [comment]
@atainter let me know if I can help in any way!  For example, it might be suitable to try the layout transition API if you're replacing imperative animation code.

**Comment by atainter** [comment]
Thanks @appleguy! I used the layout transition API initially, but I took a weird approach to updating the message group's tableView (i.e. I `beganUpdates()` in one portion of the code and `endUpdates()` in `animateLayoutTransition`). Therefore, it's not intuitive to replace the deprecated `begin/endUpdates()` with `performBatchUpdates()`. Looking back, I think it's a terrible design. I know the transition API a bit better now, so I think it makes the most sense to rewrite and restructure. I will definitely reach out if I encounter any issues.

**Comment by atainter** [comment]
I've found the source of the issue. Looks like it is not related to TableNode updates, but rather the layout for `MessageGroup`. For some reason, when the project was upgraded to 2.x the layout context stopped calculating the correct size during `animateLayoutTransition`.  I've isolated the problem to this line in the `layoutSpecThatFits`: https://github.com/eBay/NMessenger/blob/ASDK-2.1/nMessenger/Source/MessageNodes/MessageCell/MessageGroup.swift#L186.  

When I return a stack layout instead of an inset layout, the size is calculated correctly during the layout transition.
<img src="https://cloud.githubusercontent.com/assets/7866859/23683225/c81be55e-03d2-11e7-87bd-ef8361b211be.gif" width="200">

 However, when an inset layout is returned, `ASContextTransitioning` calculates the wrong size for my TableNode holding the message cells. 
<img src="https://cloud.githubusercontent.com/assets/7866859/23683234/d6109a7e-03d2-11e7-88bf-f7b181657c40.gif" width="200">

This is strange because when the MessageGroup is created with messages (i.e. no transition animation), the layout is correct.  
<img width="200" alt="screen shot 2017-03-08 at 7 03 37 am" src="https://cloud.githubusercontent.com/assets/7866859/23683122/420041e0-03d2-11e7-98c1-930f9f6ff68a.png">

Another important thing to note is that I also have to set `self.frame.size.height = context.finalFrame(for: self.messageTable).size.height` to force the ASCellNode size to change in `animateLayoutTransition` for a stack layout. I did not need to do this in ASDK 1.x. @appleguy Any insights to help fix this issue?

**Comment by appleguy** [comment]
Hmm, interesting -- Michael or Adlai on the core team might have some input here.  You should most definitely not need the ASCellNode frame size change, so that should be removed and then work from that point to get it working.  For example ASDKgram is able to animate heights, in an ASTableNode (not a collection), even by using just setNeedsLayout.

I would suggest try changing to setNeedsLayout and just compare what happens to make sure at least the layout ends up in the correct state (cell height change and all) without any other workaround lines of code.  If that does work but transitionLayoutAnimated: does not, that would be a very concrete lead.

**Comment by alexandremorgado** [comment]
Hi guys. Any updates on this issues with MessageGroup?

**Comment by atainter** [comment]
Found a solution here: https://github.com/facebook/AsyncDisplayKit/issues/2713. However, I'm getting some strange flashing issues now. I haven't had much time to work on this, but I've been experimenting on and off when I get a chance. I am 100% dedicated to fix this issue, just need some time :)

**Comment by atainter** [comment]
ASDK 2.x now supported in `1.0.80` 🎉 

https://cocoapods.org/pods/NMessenger

**Comment by alexandremorgado** [comment]
Amazing work, thank you very much @atainter 👊

**Comment by appleguy** [comment]
Woo-hoo, thank you Aaron!
